Rails Task/data_population_on_demand v2.0/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :jid_pools do
    post :threshold, on: :collection
    post :populate, on: :collection
  end

  resources :users do
    post :manual_user_addition, on: :collection
    post :bulk_user_addition, on: :collection
    post :show_users, on: :collection
    post :process_manual_user_addition, on: :collection
    post :process_bulk_user_addition, on: :collection
    post :process_show_users, on: :collection
    post :delete_user_details, on: :collection
    post :edit_user_details, on: :collection
    post :process_edit_user_details, on: :collection
  end

  root to: 'jid_pools#index'
end

Rails Task/data_population_on_demand v2.0/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails Task/data_population_on_demand v2.0/app/models/jid_pool.rb
class JidPool < ApplicationRecord

  def self.generate_unused_jids threshold_value
    unused_jids_count = JidPool.where(is_used: false).count
    if unused_jids_count == 0
      threshold_value.times do
        jid = SecureRandom.hex(4)
        unless JidPool.exists?(jid: jid)
          JidPool.create(jid: jid, is_used: false)
        end
      end
      threshold_value
    elsif (unused_jids_count < threshold_value)
      (threshold_value - unused_jids_count).times do
        jid = SecureRandom.hex(4)
        unless JidPool.exists?(jid: jid)
          JidPool.create(jid: jid, is_used: false)
        end
      end
      (threshold_value - unused_jids_count)
    else
      0
    end
  end

  def self.check_unused_jids_count
    if Threshold.count != 0
      unused_jids_count = JidPool.where(is_used: false).count
      threshold_value = Threshold.last.threshold
      if( unused_jids_count == threshold_value || unused_jids_count > threshold_value)
        "success"
      else
        "failure"
      end
    else
      "failure"
    end
  end

end

Rails Task/data_population_on_demand v2.0/app/models/threshold.rb
class Threshold < ApplicationRecord

  def self.set_threshold threshold_value
    Threshold.create(threshold: threshold_value)
  end
  
  def self.get_threshold
    if Threshold.count == 0
      return nil
    else
      Threshold.last.threshold
    end
  end
  
end

Rails Task/data_population_on_demand v2.0/app/models/user.rb
class User < ApplicationRecord

  validates :name, :email, :phone_number, :address, presence: true
  validates :email, uniqueness: {message: ': An account associated with email %{value} already exists.'}
  validates :email, :email_format => { :message => "is not valid. Please enter a vaild email address." }
  validates :phone_number, numericality: true, :length => { :minimum => 10, :maximum => 15 }

  def self.process_bulk_user_details count
    unused_jids_count = JidPool.where(is_used: false).count
    if (unused_jids_count < count || unused_jids_count < Threshold.last.threshold)
      "failure"
    else
      count.times do
        jid = JidPool.where(is_used: false).first.jid
        name = Faker::Name.name
        email = name.delete(' ') + "@gmail.com"
        phone_number = Faker::PhoneNumber.cell_phone_in_e164
        address = Faker::Address.full_address
        User.create(jid: jid, name: name, email: email, phone_number: phone_number, address: address)
        JidPool.where(jid: jid).update(is_used: true)
      end
      "success"
    end
  end

end

Rails Task/data_population_on_demand v2.0/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Rails Task/data_population_on_demand v2.0/app/controllers/jid_pools_controller.rb
class JidPoolsController < ApplicationController

  def index
  end

  def threshold
    if params[:count] == ""
      render plain: "Threshold value can't be empty."
    else
      Threshold.set_threshold(params[:count].to_i)
    end
  end

  def populate
    threshold_value = Threshold.get_threshold
    if threshold_value == nil
      render plain: "Please set threshold value first."
    else
      count_of_unused_jids_created = JidPool.generate_unused_jids(threshold_value)
      if count_of_unused_jids_created == 0
        render plain: "Enough jids already available."
      end
    end
  end

end

Rails Task/data_population_on_demand v2.0/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def manual_user_addition
    if JidPool.check_unused_jids_count == "failure"
      render plain: "Please set the threshold value if not already set / Please populate the jids as the unused jids count is less than the threshold"
    end
  end

  def bulk_user_addition
    if JidPool.check_unused_jids_count == "failure"
      render plain: "Please set the threshold value if not already set / Please populate the jids as the unused jids count is less than the threshold "
    end
  end

  def show_users
    @users = User.all
  end

  def process_manual_user_addition
    jid = JidPool.where(is_used: false).first.jid    
    user = User.create(jid: jid, name: params[:name], email: params[:email], phone_number: params[:phone_number], address: params[:address])
    if user.valid?
      JidPool.where(jid: jid).update(is_used: true)
    else
      message = ""
      for str in user.errors.full_messages
        message += str + "\n"
      end
      render plain: message, status: :not_acceptable
    end
  end

  def process_bulk_user_addition
    if params[:count] == ""
      render plain: "Count value can't be empty."
    else
      process_status = User.process_bulk_user_details(params[:count].to_i)
      if process_status == "failure"
        render plain: "Not enough jids available / Count of unused jids less than the threshold. Please populate jids first."
      end
    end
  end

  def delete_user_details
    @user = User.find(params[:id])
    @user.destroy
    redirect_to jid_pools_path
  end

  def edit_user_details
    @user = User.find(params[:id])
  end

  def process_edit_user_details
    @user = User.find(params[:id])
    if @user.update(user_params)
      render plain: "User details updated successfully."
    else
      render 'edit_user_details'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone_number, :address)
  end

end

Rails Task/data_population_on_demand v2.0/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails Task/data_population_on_demand v2.0/app/views/jid_pools/index.html.erb
<div>
<h1>Populating JIDs</h1>
<br><br>

<%= form_tag threshold_jid_pools_path, method: :post do %>
  <b><%= label_tag :count, "Enter the Threshold value:" %></b>
  <%= number_field_tag :count, nil, min: 1 %><br><br>
  <%= submit_tag "Set" %>
<% end %><br><br>

<%= form_tag populate_jid_pools_path method: :post do %>
  <%= submit_tag "Populate JIDs" %>
<% end %>

<br>
</div>

<br><br>

<div>
<h1>Populating Users</h1>
<br><br>

<%= form_tag manual_user_addition_users_path, method: :post do %>
  <%= submit_tag "Manual user addition" %>
<% end %><br>

<%= form_tag bulk_user_addition_users_path, method: :post do %>
  <%= submit_tag "Bulk user addition" %>
<% end %><br>

<%= form_tag show_users_users_path, method: :post do %>
  <%= submit_tag "Show users" %>
<% end %><br>

</div>

Rails Task/data_population_on_demand v2.0/app/views/jid_pools/populate.html.erb
<div><br>
<h2>Jids have been successfully populated.</h2>
<br>

<%= form_tag jid_pools_path, method: :get do %>  
  <%= submit_tag "Home" %>
<% end %><br><br>

</div>

Rails Task/data_population_on_demand v2.0/app/views/jid_pools/threshold.html.erb
<div><br>
<h2>Threshold value has been successfully set. Please populate the jids.</h2>
<br>

<%= form_tag jid_pools_path, method: :get do %>  
  <%= submit_tag "Home" %>
<% end %><br><br>

</div>

Rails Task/data_population_on_demand v2.0/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataPopulationOnDemand</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

Rails Task/data_population_on_demand v2.0/app/views/users/bulk_user_addition.html.erb
<div>
<h1>Bulk User Addition</h1>
<br><br>

<%= form_tag process_bulk_user_addition_users_path, method: :post do %>
  <b><%= label_tag :count, "Enter count to populate users:" %></b>
  <%= number_field_tag :count, nil, min: 1 %><br><br>
  <%= submit_tag "Submit" %>
  <%= link_to jid_pools_path, method: :get do %>
    <%= submit_tag "Back" %>
  <% end %>
<% end %><br><br>

</div>

Rails Task/data_population_on_demand v2.0/app/views/users/edit_user_details.html.erb
<div>
<h1>Edit Details</h1>
<br><br>

<%= form_with model: @user, url: process_edit_user_details_users_path(id: @user.id), method: :post, local: true do |form| %>
  <b><%= form.label :name, "Name" %></b>
  <%= form.text_field :name %><br><br>

  <b><%= form.label :email, "Email" %></b>
  <%= form.text_field :email, disabled: true %><br><br>
  
  <b><%= form.label :phone_number, "Phone Number" %></b>
  <%= form.text_field :phone_number %><br><br>

  <b><%= form.label :address, "Address" %></b>
  <%= form.text_field :address %><br><br>

  <%= form.submit "Submit" %>
  <%= link_to show_users_users_path, method: :post do %>
    <%= submit_tag "Back" %>
  <% end %>
<% end %>

</div>

Rails Task/data_population_on_demand v2.0/app/views/users/manual_user_addition.html.erb
<div>
<h1>Manual User Addition</h1>
<br><br>

<%= form_with url: process_manual_user_addition_users_path, method: :post, local: true do |form| %>
  <b><%= form.label :name, "Name" %></b>
  <%= form.text_field :name, placeholder: "Enter your name"%><br><br>

  <b><%= form.label :email, "Email" %></b>
  <%= form.text_field :email, placeholder: "Enter your email"%><br><br>
  
  <b><%= form.label :phone_number, "Phone Number" %></b>
  <%= form.text_field :phone_number, placeholder: "Enter your phone number"%><br><br>

  <b><%= form.label :address, "Address" %></b>
  <%= form.text_field :address, placeholder: "Enter your address"%><br><br>

  <%= form.submit "Submit" %>
  <%= link_to jid_pools_path, method: :get do %>
    <%= submit_tag "Back" %>
  <% end %>
<% end %>

</div>

Rails Task/data_population_on_demand v2.0/app/views/users/process_bulk_user_addition.html.erb
<div><br>
<h2>The specified count of users have been successfully created in our database.</h2>
<br>

<%= form_tag users_path, method: :get do %>  
  <%= submit_tag "Home" %>
<% end %><br><br>

</div>

Rails Task/data_population_on_demand v2.0/app/views/users/process_manual_user_addition.html.erb
<div><br>
<h2>Your details are successfully saved in our database.</h2>
<br>

<%= form_tag jid_pools_path, method: :get do %>  
  <%= submit_tag "Home" %>
<% end %><br><br>

</div>

Rails Task/data_population_on_demand v2.0/app/views/users/show_users.html.erb
<div>
<h1>List of Users</h1>
<br><br>

<% if (@users.size >= 1) %>
  <table id="data_table">
    <tr class="table_header">
      <th>S.No.</th>
      <th>Jid</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address</th>
      <th>Modify</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.jid %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.address %></td>
        <td><%= link_to "Edit", edit_user_details_users_path(id: user.id), method: :post, class: 'link_color' %> <%= link_to "Delete", delete_user_details_users_path(id: user.id), method: :post, data: { confirm: 'Are you sure?' }, class: 'link_color' %></td>
      </tr>
    <% end %>
  </table>
  <br><br>
<% else %>
  <table id="no_data_table">
    <tr class="table_header">
      <th>S.No.</th>
      <th>Jid</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address</th>
    </tr>
    <tr>
      <td colspan="6">Currently there are no user data to display</td>
    </tr>
  </table>
  <br><br>
<% end %>

<%= form_tag jid_pools_path, method: :get do %>  
  <%= submit_tag "Back" %>
<% end %>

</div>