Rails Task/data_population_on_demand v1.0/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :jid_pools, only: [:index] do
    post :populate, on: :collection
  end

  resources :users, only: [:index] do
    post :populate, on: :collection
  end

  root to: 'jid_pools#index'
end

Rails Task/data_population_on_demand v1.0/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails Task/data_population_on_demand v1.0/app/models/jid_pool.rb
class JidPool < ApplicationRecord
  def self.generate_unused_jids count
    unused_jids = []
    loop do
      jid = SecureRandom.hex(4)
      unless JidPool.exists?(jid: jid)
        unused_jids << jid
        break if unused_jids.size == count
      end
    end
    unused_jids
  end
end

Rails Task/data_population_on_demand v1.0/app/models/user.rb
class User < ApplicationRecord
    def self.generate_random_email
      SecureRandom.hex(4) + "@gmail.com"
    end
end

Rails Task/data_population_on_demand v1.0/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Rails Task/data_population_on_demand v1.0/app/controllers/jid_pools_controller.rb
class JidPoolsController < ApplicationController
  def index
    @unused_jids_count = JidPool.where(is_used: false).count
  end
  def populate
    count = params[:count].to_i
    unused_jids_count = JidPool.where(is_used: false).count
    if unused_jids_count == 0
      unused_jids = JidPool.generate_unused_jids(count)
      unused_jids.each do |jid|
        JidPool.create(jid: jid, is_used: false)
      end
    elsif ((unused_jids_count - count) < 50)
      unused_jids = JidPool.generate_unused_jids(50 - (unused_jids_count - count))
      unused_jids.each do |jid|
        JidPool.create(jid: jid, is_used: false)
      end
    end
    redirect_to jid_pools_path
  end
end

Rails Task/data_population_on_demand v1.0/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def populate
    count = params[:count].to_i
    UsersController.check_to_populate(count)
    if ((JidPool.where(is_used: false).count - count) < 50)
      unused_jids = JidPool.generate_unused_jids(50 - (JidPool.where(is_used: false).count - count) )
      unused_jids.each do |jid|
        JidPool.create(jid: jid, is_used: false)
      end
    end
    count.times do
      jid = JidPool.where(is_used: false).first.jid
      User.create(email: User.generate_random_email, jid: jid)
      JidPool.where(jid: jid).update(is_used: true)
    end
    redirect_to users_path
  end
  def UsersController.check_to_populate count
    unused_jids_count = JidPool.where(is_used: false).count
    if unused_jids_count == 0
      unused_jids = JidPool.generate_unused_jids(count)
      unused_jids.each do |jid|
        JidPool.create(jid: jid, is_used: false)
      end
    elsif ((unused_jids_count - count) < 50)
      unused_jids = JidPool.generate_unused_jids(50 - (unused_jids_count - count))
      unused_jids.each do |jid|
        JidPool.create(jid: jid, is_used: false)
      end
    end
  end
end

Rails Task/data_population_on_demand v1.0/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails Task/data_population_on_demand v1.0/app/views/jid_pools/index.html.erb
<div>
<h1>Populating JIDs</h1>
<br><br>
<%= form_tag populate_jid_pools_path, method: :post do %>
  <b><%= label_tag :count, "Enter the number of jids to populate:" %></b>
  <%= text_field_tag :count %><br><br>
  <%= submit_tag "Populate JIDs" %>
<% end %>
<br>
</div>

Rails Task/data_population_on_demand v1.0/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataPopulationOnDemand</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

Rails Task/data_population_on_demand v1.0/app/views/users/index.html.erb
<div>
<h1>Populating Users</h1>
<br><br>
<%= form_tag populate_users_path, method: :post do %>
  <b><%= label_tag :count, "Enter the number of users to populate:" %></b>
  <%= text_field_tag :count %><br><br>
  <%= submit_tag "Populate Users" %>
<% end %>
<br>
<% @users.each do |user| %>
  <p><%= user.email %> - <%= user.jid %></p>
<% end %>
</div>